namespace TaskManagerAPI.Entities
{
    /// <summary>
    /// Represents a task entity in the system.
    /// </summary>
    public class TaskItem
    {
        
        /// Unique identifier for the task.
        /// Auto-generated by the database.

        public int Id { get; set; }


        ///// The task's title or name.
        public string Title { get; set; } = string.Empty;

       
        //// Detailed description of what the task involves.
        public string Description { get; set; } = string.Empty;

       
        /////// Current status of the task.
        //// Defaults to Pending when a new task is created.
        public TaskStatus Status { get; set; } = TaskStatus.Pending;

      
        ///// Foreign key referencing the User this task is assigned to.
        public int AssignedUserId { get; set; }

   
        ///// Navigation property to the assigned User entity.
        /// Populated by Entity Framework Core for relationship navigation.
    
        public User AssignedUser { get; set; } = null!;

       
        ////// Optional deadline for when the task should be completed.
        /// Null indicates no specific deadline has been set.
        public DateTime? DueDate { get; set; }


        /// Automatically Timestamp set to current UTC time when the task is created stored in UTC.
        public DateTime CreatedAt { get; set; } = DateTime.UtcNow;
    }
}